# Generated by Django 6.0.6 on 2026-06-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Día: 0-6 para semanal (lun-dom), 1-31 para mensual, ignored para anual (usa due_date)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'Sin repetición'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('yearly', 'Anual')], default='none', max_length=10),
        ),
    ]
