# Generated by Django 6.0.6 on 2026-06-27 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_recurrence_day_task_recurrence_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assignment_status',
            field=models.CharField(choices=[('direct', 'Asignación directa'), ('pending_approval', 'Pendiente de aprobación'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='direct', max_length=20),
        ),
    ]
