# Generated by Django 6.0.6 on 2026-06-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task_assigned_by_task_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='visibility',
            field=models.CharField(choices=[('public', 'Pública'), ('private', 'Privada')], default='public', max_length=10),
        ),
    ]
