# Generated by Django 6.0.6 on 2026-07-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_is_sales_alter_notification_verb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_note',
            field=models.TextField(blank=True),
        ),
    ]
